# Generated by Django 3.0.8 on 2022-03-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20220313_1258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='Login_user',
        ),
    ]
