# Generated by Django 3.0.8 on 2022-03-10 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buildingOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
                ('building_desc', models.TextField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reward', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
