# Generated by Django 4.0.3 on 2022-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenGame', '0002_buildingoftheday_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingoftheday',
            old_name='buidling_desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='buildingoftheday',
            name='building_name',
        ),
        migrations.AddField(
            model_name='buildingoftheday',
            name='name',
            field=models.CharField(choices=[('Harrison Building', 'Harrison Building'), ('Amory Building', 'Amory Building'), ('The Forum', 'The Forum'), ('Amory', 'Amory'), ('Business School Building One', 'Business School Building One'), ('Cornwall House Swimming Pool', 'Cornwall House Swimming Pool'), ('Northcott Theatre', 'Northcott Theatre'), ('Forum', 'Forum'), ('Geoffrey Pope', 'Geoffrey Pope'), ('Great Hall', 'Great Hall'), ('Harrison', 'Harrison'), ('Hatherly', 'Hatherly'), ('Henry Wellcome Building for Biocatalysis', 'Henry Wellcome Building for Biocatalysis'), ('Innovation One | South West Institute of Technology', 'Innovation One | South West Institute of Technology'), ('Institute of Arab and Islamic Studies', 'Institute of Arab and Islamic Studies'), ('INTO International Study Centre', 'INTO International Study Centre'), ('Laver', 'Laver'), ('Library', 'Library'), ('Living Systems', 'Living Systems'), ('Mary Harris Memorial Chapel', 'Mary Harris Memorial Chapel'), ('Old Library', 'Old Library'), ('Peter Chalk Centre', 'Peter Chalk Centre'), ('Physics', 'Physics'), ('Queens', 'Queens'), ('Reed Hall', 'Reed Hall'), ('Reed Mews Wellbeing Centre', 'Reed Mews Wellbeing Centre'), ('Sir Henry Wellcome Building for Mood Disorders Research', 'Sir Henry Wellcome Building for Mood Disorders Research'), ('Sports Park', 'Sports Park'), ('Streatham Court', 'Streatham Court'), ('Student Health Centre', 'Student Health Centre'), ('Washington Singer', 'Washington Singer'), ('Xfi', 'Xfi')], default='description', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingoftheday',
            name='reward',
            field=models.CharField(choices=[('water_can.png', 'water can')], max_length=200),
        ),
    ]
