# Generated by Django 4.0.3 on 2022-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenGame', '0004_reporttoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttoadmin',
            name='email',
            field=models.CharField(default='email', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporttoadmin',
            name='username',
            field=models.CharField(default='username', max_length=200),
            preserve_default=False,
        ),
    ]
